spec:
  rules:
    - host: api.devops-ninja.ml
      http:
        paths:
          - path: /book
            pathType: Prefix
            backend:
              service:
                name: api-book
                port:
                  number: 80
          - path: /song
            pathType: Prefix
            backend:
              service:
                name: api-song
                port:
                  number: 80
          - path: /video
            pathType: Prefix
            backend:
              service:
                name: api-video
                port:
                  number: 80
