spec:
  rules:
    - host: app.multicloud-devops-ninja.pt
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mc-frontend
                port:
                  number: 80
