spec:
  rules:
    - host: cockroachdb.devops-ninja.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cockroachdb
                port:
                  number: 8080
